const router = require('express').Router()
const brandRoute = require("./brand.routes")
const categoriesRoute = require("./categories.routes")
const contractsRoute = require("./contracts.routes")
const customersRoute = require("./customers.routes")
const featureRoute = require("./feature.routes")
const laptop_stocksRoute = require("./laptop_stocks.routes")
const laptopFeaturesRoute = require("./laptopFeatures.routes")
const laptopRoute = require("./laptops.routes")
const paymentRoute = require("./payment.routes")
const sellerRoute = require("./seller.routes")

router.use("/brand", brandRoute)
router.use("/category", categoriesRoute)
router.use("/contracts", contractsRoute)
router.use("/customer", customersRoute)
router.use("/feature", featureRoute)
router.use("/stocks", laptop_stocksRoute)
router.use("/laptopFeatures", laptopFeaturesRoute)
router.use("/laptop", laptopRoute)
router.use("/payment", paymentRoute)
router.use("/seller", sellerRoute)

module.exports = router
